pipeline:
    name: docker
    identifier: docker
    allowStageExecutions: false
    projectIdentifier: Latam_Arilines
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.LATAM_SE
                          namespace: harness-delegate
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: clone
                                identifier: clone
                                spec:
                                    connectorRef: account.DockerDC
                                    image: alpine/git:latest
                                    command: |
                                        
                                        echo "Descargando proyecto correspondiente..."
                                        git clone https://github.com/damian-curiel/GKE_demo_latam.git
                          - step:
                                type: Run
                                name: bash
                                identifier: bash
                                spec:
                                    connectorRef: account.DockerDC
                                    image: badouralix/curl-jq:latest
                                    command: |
                                        #!/bin/bash

                                        cd GKE_demo_latam
                                        echo "Consultando API latam...."
                                        variables_ambiente=$(curl -H "Content-Type: application/json" https://sales-209522-default-rtdb.firebaseio.com/environment/dev.json)
                                        echo $variables_ambiente

                                        puerto=$(curl -H "Content-Type: application/json" https://sales-209522-default-rtdb.firebaseio.com/environment/dev.json | jq -r '.port')
                                        echo $puerto


                                        echo "Generando archivo App.yaml..."
                                        echo "apiVersion: apps/v1
                                        kind: Deployment
                                        metadata:
                                          name: pacifico-app
                                          labels:
                                            app: pacifico
                                        spec:
                                          selector:
                                            matchLabels:
                                              app: pacifico
                                          template:
                                            metadata:
                                              labels:
                                                app: pacifico
                                            spec:
                                              containers:
                                              - image: {{.Values.image}}
                                                name: pacifico
                                                ports:
                                                - containerPort: {{.Values.port}}" > app.yaml
                                        cat app.yaml


                                        echo "Generando archivo values.yaml..."
                                        echo "name: harness-example
                                        replicas: 1

                                        image: <+artifact.image>
                                        port: $puerto" > values.yaml
                                        cat values.yaml

                                        pwd
                                        ls -a
                                    shell: Sh
                          - step:
                                type: Run
                                name: git push
                                identifier: git_push
                                spec:
                                    connectorRef: account.DockerDC
                                    image: alpine/git:latest
                                    command: |
                                        echo "Uploading App.yaml generated..."
                                        cd GKE_demo_latam

                                        git config user.email "damian.curiel@harness.io"
                                        git config user.name "damian-curiel"
                                        git add app.yaml
                                        git add values.yaml
                                        git status
                                        git commit -m "Add harness app.yaml and values.yaml file auto-generated"
                                        git remote set-url origin https://<+secrets.getValue("account.git_dc_pat")>@github.com/damian-curiel/GKE_demo_latam.git
                                        git push -u origin master


                                        #clean
                                        git rm app.yaml
                                        git rm values.yaml
                                        git commit -m "Deleted the file from the git repository"
                                        git push -u origin master
                                when:
                                    stageStatus: Failure
                                failureStrategies: []
                          - step:
                                type: Run
                                name: git remove
                                identifier: git_remove
                                spec:
                                    connectorRef: account.DockerDC
                                    image: alpine/git:latest
                                    command: |-
                                        echo "removing files"
                                        cd GKE_demo_latam

                                        git rm app.yaml
                                        git rm values.yaml
                                        git status
                                        git commit -m "Deleted the file from the git repository"
                                        git remote set-url origin https://<+secrets.getValue("account.git_dc_pat")>@github.com/damian-curiel/GKE_demo_latam.git
                                        git push -u origin master
