pipeline:
    name: docker
    identifier: docker
    allowStageExecutions: false
    projectIdentifier: Latam_Arilines
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.LATAM_SE
                          namespace: harness-delegate
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: git clone
                                identifier: git_clone
                                spec:
                                    connectorRef: account.DockerDC
                                    image: alpine/git:latest
                                    command: |-
                                        echo "Borrando temporales..."

                                        #rm -r /harness/*
                                        pwd
                                        ls

                                        echo "Descargando proyecto correspondiente..."


                                        git clone https://github.com/damian-curiel/GKE_demo_latam.git
                                        cd GKE_demo_latam


                                        echo "Proyecto descargado:"
                                        pwd
                                        ls -a
                          - step:
                                type: Run
                                name: compile
                                identifier: compile
                                spec:
                                    connectorRef: account.DockerDC
                                    image: maven:3-openjdk-8
                                    command: |-
                                        echo "Listing Directory and files"
                                        cd GKE_demo_latam
                                        pwd
                                        ls -ltra

                                        echo "Starting Build"

                                        mvn -B -DskipTests clean package

                                        echo "Build Finished"
                                when:
                                    stageStatus: Failure
                                failureStrategies: []
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: push
                                identifier: push
                                spec:
                                    connectorRef: account.DockerDC
                                    repo: fcuriel/pacifico
                                    tags:
                                        - <+pipeline.sequenceId>
                                    context: /harness/GKE_demo_latam/
