pipeline:
    name: docker
    identifier: docker
    allowStageExecutions: false
    projectIdentifier: Latam_Arilines
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.LATAM_SE
                          namespace: harness-delegate
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: bash
                                identifier: bash
                                spec:
                                    connectorRef: account.DockerDC
                                    image: badouralix/curl-jq:latest
                                    command: |
                                        #!/bin/bash

                                        echo "Consultando API latam...."
                                        variables_ambiente=$(curl -H "Content-Type: application/json" https://sales-209522-default-rtdb.firebaseio.com/environment/dev.json)
                                        echo $variables_ambiente

                                        puerto=$(curl -H "Content-Type: application/json" https://sales-209522-default-rtdb.firebaseio.com/environment/dev.json | jq -r '.port')
                                        echo $puerto


                                        echo "Generando archivo App.yaml..."
                                        echo "apiVersion: apps/v1
                                        kind: Deployment
                                        metadata:
                                          name: pacifico-app
                                          labels:
                                            app: pacifico
                                        spec:
                                          selector:
                                            matchLabels:
                                              app: pacifico
                                          template:
                                            metadata:
                                              labels:
                                                app: pacifico
                                            spec:
                                              containers:
                                              - image: {{.Values.image}}
                                                name: pacifico
                                                ports:
                                                - containerPort: {{.Values.port}}" > app.yaml
                                        cat app.yaml


                                        echo "Generando archivo values.yaml..."
                                        echo "name: harness-example
                                        replicas: 1

                                        image: <+artifact.image>
                                        port: $puerto" > values.yaml
                                        cat values.yaml

                                        pwd
                                        ls -a
                                    shell: Sh
